server:
  port: 5000

spring:
  cloud:
    config:
      name: config-server
      server:
        git:
          uri: https://github.com/OlgaFedorova/airline.git
          search-paths: 'config-files/{application}'